services:
  db:
    image: postgres:latest
    container_name: mi_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: mi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/db_name?schema=public"
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --reload
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
